package com.godesii.godesii_services.entity.auth;

public enum Permission {

    /* USER */
    USER_CREATE, USER_READ, USER_UPDATE, USER_DELETE, USER_ASSIGN_ROLE,
    USER_BLOCK, USER_UNBLOCK,

    /* PRODUCT */
    PRODUCT_CREATE, PRODUCT_READ, PRODUCT_UPDATE, PRODUCT_DELETE, PRODUCT_APPROVE,

    /* INVENTORY */
    INVENTORY_READ, INVENTORY_UPDATE,

    /* ORDER */
    ORDER_CREATE, ORDER_READ, ORDER_READ_ALL, ORDER_UPDATE,
    ORDER_CANCEL, ORDER_APPROVE, ORDER_ASSIGN_DELIVERY, ORDER_REFUND,

    /* DELIVERY */
    DELIVERY_VIEW_ASSIGNED, DELIVERY_ACCEPT, DELIVERY_REJECT,
    DELIVERY_PICKUP, DELIVERY_IN_TRANSIT, DELIVERY_COMPLETE,

    /* PAYMENT */
    PAYMENT_INITIATE, PAYMENT_READ, PAYMENT_READ_ALL, PAYMENT_REFUND,

    /* ================= RESTAURANT ================= */
    RESTAURANT_CREATE,
    RESTAURANT_READ,
    RESTAURANT_UPDATE,
    RESTAURANT_APPROVE,
    RESTAURANT_SUSPEND,

    /* VENDOR */
    VENDOR_CREATE, VENDOR_READ, VENDOR_UPDATE, VENDOR_APPROVE,

    /* REVIEW */
    REVIEW_CREATE, REVIEW_READ, REVIEW_DELETE,

    /* SUPPORT */
    SUPPORT_TICKET_CREATE, SUPPORT_TICKET_READ, SUPPORT_TICKET_CLOSE,

    /* REPORT */
    REPORT_VIEW_USERS, REPORT_VIEW_ORDERS, REPORT_VIEW_SALES, REPORT_VIEW_REVENUE,

    /* SYSTEM */
    SYSTEM_CONFIG_READ, SYSTEM_CONFIG_UPDATE
}
