# Datasource config
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/villsyn?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:villsyn_user}
    password: ${DB_PASSWORD:AMRI9&Shashank?Vipin7}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: false
    hikari:
      minimumIdle: 2
      maximumIdle: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        search:
          backend:
            type: lucene
            directory:
              root: ./lucene-indexes
            analysis:
              configurer: com.godesii.godesii_services.config.FoodSearchAnalysisConfigurer
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml

#Swagger/OpenAPI config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs


# App Config
app:

  twilio:
    sid: ${TWILIO_SID:AC283554d38ab9900e0c8281d88f3613af}
    token: ${TWILIO_TOKEN:01b2a73671726d08a718804e1d521fca}
    phoneNo: ${TWILIO_PHONE_NUMBER:+17176708304}

  aws:
    s3:
      accessKey: AKIA3WMTVBRQTKYR6RGL
      secretKey: ${AWS_SECRET_KEY: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}
      region: ap-south-1
      bucketName: villsyn

  jwt:
    access-token:
      expiration: 360000
    refresh-token:
      expiration: 360000
    encryptor:
      password: 2*d0bCr6#:=5
      salt: 626F6F746966756C
